version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: npm test

  sonarcloud:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.organization=ST10090916-CianBrink \
              -Dsonar.projectKey=SHA256:Buf7gMTvFwD2nIqo6cgUhpXCm+NCDqOVyvM5K8YqtTc \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build-test-and-analyze:
    jobs:
      - build-and-test
      - sonarcloud:
          requires:
            - build-and-test
