version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16-browsers
    working_directory: ~/project

jobs:
  install-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Navigate to Frontend and Install Dependencies
          command: |
            cd frontend
            npm install

  install-backend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Navigate to Backend and Install Dependencies
          command: |
            cd backend
            npm install

  test-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Navigate to Frontend and Run Tests
          command: |
            cd frontend
            npm run test

  test-backend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Navigate to Backend and Run Tests
          command: |
            cd backend
            npm run test

  build-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Navigate to Frontend and Build
          command: |
            cd frontend
            npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-frontend
      - install-backend
      - test-frontend:
          requires:
            - install-frontend
      - test-backend:
          requires:
            - install-backend
      - build-frontend:
          requires:
            - test-frontend
