version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16.13.0 # Use a valid and stable Node.js version
  backend-executor:
    docker:
      - image: circleci/node:16.13.0

jobs:
  install-and-test-frontend:
    executor: node-executor
    working_directory: ~/project/frontend
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: npm install
      - run:
          name: Test Frontend
          command: npm test

  install-and-test-backend:
    executor: backend-executor
    working_directory: ~/project/backend
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: npm install
      - run:
          name: Test Backend
          command: npm test

  sonar-analysis:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=ST10090916-CianBrink_CDKJY_APDS7311_POE \
              -Dsonar.organization=st10090916-cianbrink \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=a31576c179f1f4dc87777e82c93ba51ca677bb4b

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-and-test-frontend
      - install-and-test-backend:
          requires:
            - install-and-test-frontend
      - sonar-analysis:
          requires:
            - install-and-test-backend
