version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:20  # Use the Node.js version you are using locally

jobs:
  install-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            npm install

  install-backend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            npm install

  test-frontend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Test Frontend
          command: |
            cd frontend
            npm test

  test-backend:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Test Backend
          command: |
            cd backend
            npm test

  sonar-scan:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Sonar Scanner
          command: |
            npm install -g sonar-scanner
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=ST10090916-CianBrink_CDKJY_APDS7311_POE \
              -Dsonar.organization=st10090916-cianbrink \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=a31576c179f1f4dc87777e82c93ba51ca677bb4b

workflows:
  version: 2
  build-test-and-scan:
    jobs:
      - install-frontend
      - install-backend:
          requires:
            - install-frontend
      - test-frontend:
          requires:
            - install-frontend
      - test-backend:
          requires:
            - install-backend
      - sonar-scan:
          requires:
            - test-frontend
            - test-backend
